openapi: 3.0.1
info:
  description: 'Simple open api file'
  title: 'Simple open api file'
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
paths:
  /hello:
    get:
      description: hello world!
      operationId: helloWorld
      responses:
        200:
          content:
            application/json:
              schema:
                type: string
          description: successful operation